from star_craft.adapter.outbound.kerrigan_context_router_repository import KerriganContextRouterRepository
from star_craft.adapter.outbound.raynor_spoke_registry_repository import RaynorSpokeRegistryRepository
from star_craft.app.ports.input.kerrigan_context_router_use_case import KerriganContextRouterUseCase
from star_craft.app.ports.input.raynor_spoke_registry_use_case import RaynorSpokeRegistryUseCase
from star_craft.app.use_cases.kerrigan_context_router_interactor import KerriganContextRouterInteractor
from star_craft.app.use_cases.raynor_spoke_registry_interactor import RaynorSpokeRegistryInteractor


def get_kerrigan_use_case() -> KerriganContextRouterUseCase:
    return KerriganContextRouterInteractor(KerriganContextRouterRepository())


def get_raynor_use_case() -> RaynorSpokeRegistryUseCase:
    return RaynorSpokeRegistryInteractor(RaynorSpokeRegistryRepository())
