services:
  # FastAPI 백엔드 서비스
  backend:
    build:
      context: ./tailor
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./tailor/.env
    volumes:
      - ./tailor:/tailor

  # Next.js 프론트엔드 서비스
  frontend:
    build:
      context: ./taylor
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./taylor/.env.local
    depends_on:
      - backend
